### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by RavHilton** [jontitmus-code/SuiteCRM8_docker#9] opened 2022-01-31 01:57 UTC
OK, I'm attempting this on an Alpine Linux base, with Docker and Docker-Compose installed, which *should* be fine as I run a boat load of other docker setups this way.

Also, using SugarCRM 8.0.3 as that is the current version.

I get the following errors (amongst a lot of others):

Step 22/25 : RUN npm install -g @angular/cli
 ---> Running in 27119d0e69dd
/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng.js

> @angular/cli@13.2.0 postinstall /usr/local/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

npm WARN notsup Unsupported engine for @angular/cli@13.2.0: wanted: {"node":"^12.20.0 || ^14.15.0 || >=16.10.0","npm":"^6.11.0 || ^7.5.6 || >=8.0.0","yarn":">= 1.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @angular/cli@13.2.0
npm WARN notsup Unsupported engine for @angular-devkit/architect@0.1302.0: wanted: {"node":"^12.20.0 || ^14.15.0 || >=16.10.0","npm":"^6.11.0 || ^7.5.6 || >=8.0.0","yarn":">= 1.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @angular-devkit/architect@0.1302.0
npm WARN notsup Unsupported engine for @angular-devkit/schematics@13.2.0: wanted: {"node":"^12.20.0 || ^14.15.0 || >=16.10.0","npm":"^6.11.0 || ^7.5.6 || >=8.0.0","yarn":">= 1.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @angular-devkit/schematics@13.2.0
npm WARN notsup Unsupported engine for pacote@12.0.3: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: pacote@12.0.3
npm WARN notsup Unsupported engine for @angular-devkit/core@13.2.0: wanted: {"node":"^12.20.0 || ^14.15.0 || >=16.10.0","npm":"^6.11.0 || ^7.5.6 || >=8.0.0","yarn":">= 1.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @angular-devkit/core@13.2.0
npm WARN notsup Unsupported engine for open@8.4.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: open@8.4.0
npm WARN notsup Unsupported engine for @schematics/angular@13.2.0: wanted: {"node":"^12.20.0 || ^14.15.0 || >=16.10.0","npm":"^6.11.0 || ^7.5.6 || >=8.0.0","yarn":">= 1.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @schematics/angular@13.2.0
npm WARN notsup Unsupported engine for npm-registry-fetch@12.0.1: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: npm-registry-fetch@12.0.1
npm WARN notsup Unsupported engine for npmlog@6.0.0: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: npmlog@6.0.0
npm WARN notsup Unsupported engine for @npmcli/fs@1.1.0: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @npmcli/fs@1.1.0
npm WARN notsup Unsupported engine for gauge@4.0.0: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: gauge@4.0.0
npm WARN notsup Unsupported engine for make-fetch-happen@10.0.0: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: make-fetch-happen@10.0.0

+ @angular/cli@13.2.0
added 187 packages from 134 contributors in 17.178s
Removing intermediate container 27119d0e69dd
 ---> 127e38aa099a
Step 23/25 : RUN npm install --global yarn
 ---> Running in e2efbe6b8363

**Comment by wilj** [comment] 2022-01-31 03:28
Those are warnings, not errors.  And you only need them if you're running it in development mode.  What output do you get when you run it after building?

I have a fork with an automated installer and additional logging, if you want to try it: [https://github.com/wilj/SuiteCRM8_docker](https://github.com/wilj/SuiteCRM8_docker)

**Comment by RavHilton** [comment] 2022-01-31 06:08
It fails to run.

Digest: sha256:90feab83dd4b831c0f69d9329ab205dab5fdd9c24b9b2e5a81dd9a482f02c8e4
Status: Downloaded newer image for phpmyadmin/phpmyadmin:latest
Creating suitecrm8_docker_mysql_crm_1 ... 
Creating suitecrm8_docker_suitecrm_1  ... error

ERROR: for suitecrm8_docker_suitecrm_1  Cannot start service suitecrm: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/SuiCreating suitecrm8_docker_mysql_crm_1 ... error
wn

ERROR: for suitecrm8_docker_mysql_crm_1  Cannot start service mysql_crm: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/SuiteCRM8_docker/docker/data/mysql" to rootfs at "/var/lib/mysql" caused: stat /root/SuiteCRM8_docker/docker/data/mysql: permission denied: unknown

ERROR: for suitecrm  Cannot start service suitecrm: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/SuiteCRM8_docker/logs/apache" to rootfs at "/var/log/apache2" caused: stat /root/SuiteCRM8_docker/logs/apache: permission denied: unknown

ERROR: for mysql_crm  Cannot start service mysql_crm: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/SuiteCRM8_docker/docker/data/mysql" to rootfs at "/var/lib/mysql" caused: stat /root/SuiteCRM8_docker/docker/data/mysql: permission denied: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by RavHilton** [comment] 2022-01-31 06:21
Oohhh, that gitpod.io fork is nice, and boot, runs and works fine, but doesn't allow me to install it in a local environment.

(I've not seen gitpod before - that's rather impressive.)

**Comment by wilj** [comment] 2022-01-31 14:08
> ERROR: for suitecrm Cannot start service suitecrm: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/SuiteCRM8_docker/logs/apache" to rootfs at "/var/log/apache2" caused: stat /root/SuiteCRM8_docker/logs/apache: permission denied: unknown

Those are caused by a mismatch between user and directory ownership for the volume mounts.  They can vary from host to host, so my fork uses Docker volumes instead of local directory mounts to prevent this issue.


> Oohhh, that gitpod.io fork is nice, and boot, runs and works fine, but doesn't allow me to install it in a local environment.

I updated the docs for running my fork locally with Docker + Docker Compose, or Vagrant + Virtualbox.


> (I've not seen gitpod before - that's rather impressive.)

Yeah, Gitpod has been a game changer for me, having all my projects ready-to-code from the click of a link on whatever computer I happen to be using at the moment.  Now I use an old Chromebook for development as much as I do my workstation, just because I can spin something up and work on it whenever/wherever I feel like.

**Comment by RavHilton** [comment] 2022-03-15 01:44
OK, So I have had another chance to look into this.  SuiteCRM 8.0.4 is now out...

Alpine Linux 3.15 base, cloned the repo, upped the docker-compose, containers started...

* It seems that the suitecrm_suitecrm_1 is now suitecrm8_docker_suitecrm_1

* There is nothing in the docker container /var/www/html/SuiteCRM8 folder except for the "logs" folder.  There is no "bin" folder.  But yes, it is there on the host itself...

* I can't seem to get past this point where, basically, the Containers are up, Apache is running, and I can't configure SuiteCRM 8.

**Comment by wilj** [comment] 2022-05-02 16:39
I'm not sure if it's the cause of your problem, but I just noticed this: [https://github.com/jontitmus-code/SuiteCRM8_docker/blob/a32fab9f6e43c496d9094fd3c96e1813e2c14d16/Dockerfile#L1](https://github.com/jontitmus-code/SuiteCRM8_docker/blob/a32fab9f6e43c496d9094fd3c96e1813e2c14d16/Dockerfile#L1)

The Dockerfile is using "ubuntu:latest", which is now 22.04, and some of the package names have changed.  I had to change it to "ubuntu;focal" in my fork to get things working again.

**Comment by jontitmus-code** [comment] 2024-06-27 12:44
Closing due to age, feel free to open new issue for anything related or ongoing issues.

**Closed as completed by jontitmus-code** 2024-06-27 12:44 UTC
